# ===================================
#  Reorder Behavior Config
# ===================================

# Model Class name
modelClass: Pensoft\TrainingCorner\Models\Training

# Key column name to use for the sort order
orderColumn: sort_order

# Title to use for the reorder page
title: Reorder Trainings

# The attribute on the model to use for the display name
nameFrom: name